name: Verifications

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: write
  checks: write

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}'
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  VITE_API_MOCKING: 'enabled'
  HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
  HAPPO_API_SECRET: ${{ secrets.HAPPO_API_SECRET }}
  CURRENTS_PROJECT_ID: ${{ secrets.CURRENTS_PROJECT_ID }}
  CURRENTS_RECORD_KEY: ${{ secrets.CURRENTS_RECORD_KEY }}

jobs:
  code_validation:
    strategy:
      fail-fast: false
      matrix:
        validation_script: ['lint', 'type-check', 'format:check', 'test:ci']
    name: 'Code Validation: ${{ matrix.validation_script }}'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Run script
        run: pnpm ${{ matrix.validation_script }}

      - name: Upload tests coverage report
        if: ${{ !cancelled() && github.event.action != 'closed' && matrix.validation_script == 'test:ci' }}
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          report_type: 'coverage'

      - name: Upload tests result report
        if: ${{ !cancelled() && github.event.action != 'closed' && matrix.validation_script == 'test:ci' }}
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          report_type: 'test_results'

  e2e-tests:
    name: E2E tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: mcr.microsoft.com/playwright:v1.57.0-noble
      options: --user 1001
    steps:
      - name: Checkout repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Build webapp
        run: pnpm build # VITE_API_MOCKING is set to 'enabled' at the top of the file

      - name: Run tests
        run: pnpm run happo -- pnpm run e2e
