name: Verifications

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main

permissions:
  contents: read
  actions: write
  checks: write

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}'
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  NEXT_PUBLIC_API_MOCKING: 'enabled'
  NONCE_ID: '${{ github.run_id || github.event.pull_request.head.label || github.head_ref || github.ref }}'
  HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
  HAPPO_API_SECRET: ${{ secrets.HAPPO_API_SECRET }}
  CURRENTS_PROJECT_ID: ${{ secrets.CURRENTS_PROJECT_ID }}
  CURRENTS_RECORD_KEY: ${{ secrets.CURRENTS_RECORD_KEY }}

jobs:
  code_validation:
    strategy:
      fail-fast: false
      matrix:
        validation_script: ['lint', 'type-check', 'format:check', 'test:ci']
    name: 'Code Validation: ${{ matrix.validation_script }}'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Run script
        run: pnpm ${{ matrix.validation_script }}

      - name: Upload tests coverage report
        if: ${{ !cancelled() && github.event.action != 'closed' && matrix.validation_script == 'test:ci' }}
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          report_type: 'coverage'

      - name: Upload tests result report
        if: ${{ !cancelled() && github.event.action != 'closed' && matrix.validation_script == 'test:ci' }}
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          report_type: 'test_results'

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup project
        uses: ./.github/actions/setup-project

      # https://nextjs.org/docs/app/guides/ci-build-caching#github-actions
      - name: Cache bundle
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        id: cache-bundle
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextcache-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextcache-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Build
        run: pnpm build

      - name: Upload bundle artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: bundle
          if-no-files-found: error
          include-hidden-files: true
          path: .next

  e2e-tests:
    name: E2E tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    container:
      image: mcr.microsoft.com/playwright:v1.57.0-noble
      options: --user 1001
    strategy:
      fail-fast: false
      matrix:
        shard_index: [1, 2, 3]
    steps:
      - name: Checkout repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Download bundle artifact
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: bundle
          path: .next

      - name: Run tests
        run: pnpm run happo --nonce $NONCE_ID -- pnpm run e2e --shard=${{matrix.shard_index}}/${{strategy.job-total}}

  e2e-finalize:
    name: E2E finalize
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ !cancelled() }}
    needs: e2e-tests
    steps:
      - name: Checkout repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Finalize Happo
        run: pnpm run happo finalize --nonce $NONCE_ID
